# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 13:26
from __future__ import unicode_literals

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, verbose_name='date pubished')),
                ('likes', models.IntegerField(default=0)),
                ('thumbnail', models.FileField(blank=True, upload_to=article.models.get_upload_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, verbose_name='date pubished')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
